/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_kherud_llama_LlamaUtils */

#ifndef _Included_de_kherud_llama_LlamaUtils
#define _Included_de_kherud_llama_LlamaUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_kherud_llama_LlamaUtils
 * Method:    supportsGpuOffloadNative
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_kherud_llama_LlamaUtils_supportsGpuOffloadNative
  (JNIEnv *, jclass);

/*
 * Class:     de_kherud_llama_LlamaUtils
 * Method:    supportsMmapNative
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_kherud_llama_LlamaUtils_supportsMmapNative
  (JNIEnv *, jclass);

/*
 * Class:     de_kherud_llama_LlamaUtils
 * Method:    supportsMlockNative
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_kherud_llama_LlamaUtils_supportsMlockNative
  (JNIEnv *, jclass);

/*
 * Class:     de_kherud_llama_LlamaUtils
 * Method:    supportsRpcNative
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_kherud_llama_LlamaUtils_supportsRpcNative
  (JNIEnv *, jclass);

/*
 * Class:     de_kherud_llama_LlamaUtils
 * Method:    maxDevicesNative
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_kherud_llama_LlamaUtils_maxDevicesNative
  (JNIEnv *, jclass);

/*
 * Class:     de_kherud_llama_LlamaUtils
 * Method:    maxParallelSequencesNative
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_kherud_llama_LlamaUtils_maxParallelSequencesNative
  (JNIEnv *, jclass);

/*
 * Class:     de_kherud_llama_LlamaUtils
 * Method:    printSystemInfoNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_kherud_llama_LlamaUtils_printSystemInfoNative
  (JNIEnv *, jclass);

/*
 * Class:     de_kherud_llama_LlamaUtils
 * Method:    timeUsNative
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_kherud_llama_LlamaUtils_timeUsNative
  (JNIEnv *, jclass);

/*
 * Class:     de_kherud_llama_LlamaUtils
 * Method:    setLogCallbackNative
 * Signature: (Lde/kherud/llama/LlamaUtils/LogCallback;)V
 */
JNIEXPORT void JNICALL Java_de_kherud_llama_LlamaUtils_setLogCallbackNative
  (JNIEnv *, jclass, jobject);

/*
 * Class:     de_kherud_llama_LlamaUtils
 * Method:    splitPathNative
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_kherud_llama_LlamaUtils_splitPathNative
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     de_kherud_llama_LlamaUtils
 * Method:    initializeBackendNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_kherud_llama_LlamaUtils_initializeBackendNative
  (JNIEnv *, jclass);

/*
 * Class:     de_kherud_llama_LlamaUtils
 * Method:    freeBackendNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_kherud_llama_LlamaUtils_freeBackendNative
  (JNIEnv *, jclass);

/*
 * Class:     de_kherud_llama_LlamaUtils
 * Method:    initializeNumaNative
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_kherud_llama_LlamaUtils_initializeNumaNative
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
